[2024-03-22T00:12:37.225+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_virtualenvs.print_python_fact manual__2024-03-22T00:12:35.177392+00:00 [queued]>
[2024-03-22T00:12:37.231+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_virtualenvs.print_python_fact manual__2024-03-22T00:12:35.177392+00:00 [queued]>
[2024-03-22T00:12:37.231+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-22T00:12:37.241+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): print_python_fact> on 2024-03-22 00:12:35.177392+00:00
[2024-03-22T00:12:37.244+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-03-22T00:12:37.248+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'testing_virtualenvs', 'print_python_fact', 'manual__2024-03-22T00:12:35.177392+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/testing_virtualenvs.py', '--cfg-path', '/tmp/tmp_x9dvnvz']
[2024-03-22T00:12:37.251+0000] {standard_task_runner.py:88} INFO - Job 101: Subtask print_python_fact
[2024-03-22T00:12:37.290+0000] {task_command.py:423} INFO - Running <TaskInstance: testing_virtualenvs.print_python_fact manual__2024-03-22T00:12:35.177392+00:00 [running]> on host 4b8b907c2725
[2024-03-22T00:12:37.345+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_virtualenvs' AIRFLOW_CTX_TASK_ID='print_python_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-03-22T00:12:35.177392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-22T00:12:35.177392+00:00'
[2024-03-22T00:12:37.348+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvbqvo45l7 --system-site-packages --python=python
[2024-03-22T00:12:37.355+0000] {process_utils.py:186} INFO - Output:
[2024-03-22T00:12:38.417+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 641ms
[2024-03-22T00:12:38.419+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvbqvo45l7, clear=False, no_vcs_ignore=False, global=True)
[2024-03-22T00:12:38.419+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-03-22T00:12:38.420+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-03-22T00:12:38.421+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-03-22T00:12:38.470+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvbqvo45l7/bin/pip install -r /tmp/venvbqvo45l7/requirements.txt
[2024-03-22T00:12:38.477+0000] {process_utils.py:186} INFO - Output:
[2024-03-22T00:12:40.221+0000] {process_utils.py:190} INFO - Collecting randfacts==0.21.0 (from -r /tmp/venvbqvo45l7/requirements.txt (line 1))
[2024-03-22T00:12:40.592+0000] {process_utils.py:190} INFO -   Downloading randfacts-0.21.0-py3-none-any.whl.metadata (4.5 kB)
[2024-03-22T00:12:40.652+0000] {process_utils.py:190} INFO - Downloading randfacts-0.21.0-py3-none-any.whl (273 kB)
[2024-03-22T00:12:40.816+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.8/273.8 kB 1.7 MB/s eta 0:00:00
[2024-03-22T00:12:44.218+0000] {process_utils.py:190} INFO - Installing collected packages: randfacts
[2024-03-22T00:12:44.236+0000] {process_utils.py:190} INFO - Successfully installed randfacts-0.21.0
[2024-03-22T00:12:44.614+0000] {process_utils.py:190} INFO - 
[2024-03-22T00:12:44.615+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.0
[2024-03-22T00:12:44.616+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-03-22T00:12:44.742+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvbqvo45l7/bin/python /tmp/venv-call9clzgl1o/script.py /tmp/venv-call9clzgl1o/script.in /tmp/venv-call9clzgl1o/script.out /tmp/venv-call9clzgl1o/string_args.txt /tmp/venv-call9clzgl1o/termination.log
[2024-03-22T00:12:44.749+0000] {process_utils.py:186} INFO - Output:
[2024-03-22T00:12:45.833+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-03-22T00:12:45.833+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call9clzgl1o/script.py", line 33, in <module>
[2024-03-22T00:12:45.834+0000] {process_utils.py:190} INFO -     res = print_python_fact(*arg_dict["args"], **arg_dict["kwargs"])
[2024-03-22T00:12:45.834+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call9clzgl1o/script.py", line 29, in print_python_fact
[2024-03-22T00:12:45.834+0000] {process_utils.py:190} INFO -     print(randfacts.get_joke())
[2024-03-22T00:12:45.834+0000] {process_utils.py:190} INFO - AttributeError: module 'randfacts' has no attribute 'get_joke'
[2024-03-22T00:12:46.016+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
module 'randfacts' has no attribute 'get_joke'
[2024-03-22T00:12:46.022+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=testing_virtualenvs, task_id=print_python_fact, execution_date=20240322T001235, start_date=20240322T001237, end_date=20240322T001246
[2024-03-22T00:12:46.031+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 101 for task print_python_fact (Process returned non-zero exit status 1.
module 'randfacts' has no attribute 'get_joke'; 69)
[2024-03-22T00:12:46.062+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-22T00:12:46.075+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
