[2024-03-21T21:53:39.681+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-03-21T21:53:36.341796+00:00 [queued]>
[2024-03-21T21:53:39.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator.external_python manual__2024-03-21T21:53:36.341796+00:00 [queued]>
[2024-03-21T21:53:39.690+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-03-21T21:53:39.705+0000] {taskinstance.py:2191} INFO - Executing <Task(ExternalPythonOperator): external_python> on 2024-03-21 21:53:36.341796+00:00
[2024-03-21T21:53:39.711+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2024-03-21T21:53:39.714+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator', 'external_python', 'manual__2024-03-21T21:53:36.341796+00:00', '--job-id', '74', '--raw', '--subdir', '/home/***/.local/lib/python3.8/site-packages/***/example_dags/example_python_operator.py', '--cfg-path', '/tmp/tmp3ixlonn8']
[2024-03-21T21:53:39.717+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask external_python
[2024-03-21T21:53:39.764+0000] {task_command.py:423} INFO - Running <TaskInstance: example_python_operator.external_python manual__2024-03-21T21:53:36.341796+00:00 [running]> on host d2feb6af224b
[2024-03-21T21:53:39.834+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator' AIRFLOW_CTX_TASK_ID='external_python' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T21:53:36.341796+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-21T21:53:36.341796+00:00'
[2024-03-21T21:53:40.918+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python /tmp/venv-callc9gxm1wr/script.py /tmp/venv-callc9gxm1wr/script.in /tmp/venv-callc9gxm1wr/script.out /tmp/venv-callc9gxm1wr/string_args.txt /tmp/venv-callc9gxm1wr/termination.log
[2024-03-21T21:53:40.933+0000] {process_utils.py:186} INFO - Output:
[2024-03-21T21:53:43.071+0000] {process_utils.py:190} INFO - Running task via /usr/local/bin/python
[2024-03-21T21:53:43.072+0000] {process_utils.py:190} INFO - Sleeping
[2024-03-21T21:53:43.073+0000] {process_utils.py:190} INFO - Please wait...
[2024-03-21T21:53:44.072+0000] {process_utils.py:190} INFO - Please wait...
[2024-03-21T21:53:45.073+0000] {process_utils.py:190} INFO - Please wait...
[2024-03-21T21:53:46.074+0000] {process_utils.py:190} INFO - Please wait...
[2024-03-21T21:53:47.076+0000] {process_utils.py:190} INFO - Finished
[2024-03-21T21:53:47.246+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-21T21:53:47.259+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=example_python_operator, task_id=external_python, execution_date=20240321T215336, start_date=20240321T215339, end_date=20240321T215347
[2024-03-21T21:53:47.316+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-21T21:53:47.341+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
