[2024-03-22T00:10:03.033+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: use_mr_worldwide.mr_worldwide_addition scheduled__2024-03-21T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
